spring.datasource.url=jdbc:h2:file:./data/moneynote;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;AUTO_SERVER=TRUE;TRACE_LEVEL_FILE=0
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=${DB_PASSWORD:78p7gkc1}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=false

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.jakarta.persistence.sharedCache.mode=NONE
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_by.default_null_ordering=last

#spring.mvc.servlet.path=/api/v1
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
server.port=9092

spring.data.web.pageable.size-parameter=pageSize
spring.data.web.pageable.page-parameter=current
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.one-indexed-parameters=true
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.prefix=
spring.data.web.pageable.qualifier-delimiter=_

spring.messages.encoding=UTF-8
spring.messages.basename=i18n/messages
spring.messages.cache-duration=3600

server.tomcat.max-http-form-post-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.max-file-size=100MB